services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: football_db
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: miharbiikun7625
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - football-network

  airflow:
    container_name: football_airflow
    image: apache/airflow:3.0.0
    ports:
      - "8000:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_DB: football_db
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: miharbiikun7625
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 1001
    depends_on:
      - postgres
    networks:
      - football-network
    command: >
      bash -c "airflow db migrate && airflow standalone"

networks:
  football-network:
    driver: bridge
